// Names of the game's data (stage 2). Every name is the ORIGINAL address (memory keeps the original layout);
// generated by tools/name-data.mjs from the data dictionary. Meanings and evidence: docs/DATA.md.

// Library struct layouts (re/LIBRARY.md).
export const PCX = { SIZE: 0x398, header: 0x0, palette: 0x94, buffer: 0x394 };
export const SPRITE = { SIZE: 0x18c, x: 0x0, y: 0x4, width: 0x8, height: 0xc, counter1: 0x10, counter2: 0x14, counter3: 0x18, threshold1: 0x1c, threshold2: 0x20, threshold3: 0x24, frames: 0x28, currFrame: 0x168, numFrames: 0x16c, state: 0x170, background: 0x174, xClip: 0x178, yClip: 0x17c, widthClip: 0x180, heightClip: 0x184, visible: 0x188 };
export const MPLAY = { SIZE: 0x10, track: 0x0, count: 0x4 };
export const DPLAY = { SIZE: 0x10, snd: 0x0, count: 0x4, priority: 0x6, presnd: 0x8, soundnum: 0xa };
export const DETECT_OVERRIDES = { SIZE: 0x10, port: 0x0, dma: 0x2, irq: 0x4 };
export const DETECT_RESULTS = { SIZE: 0x40 };
export const IDEAL = { SIZE: 0x10, musicType: 0x0, digitalType: 0x2, digitalRate: 0x4, digitalVoices: 0x6, field8: 0x8 };
export const PALETTE = { SIZE: 0x308, startReg: 0x0, endReg: 0x4, colors: 0x8 };

// Scan codes (set 1) of the keys the game reads, for keyboardState slots.
export const KEY = { esc: 0x1, d1: 0x2, d2: 0x3, d3: 0x4, d4: 0x5, d5: 0x6, d6: 0x7, d7: 0x8, d8: 0x9, d9: 0xa, d0: 0xb, q: 0x10, w: 0x11, e: 0x12, r: 0x13, t: 0x14, y: 0x15, u: 0x16, i: 0x17, o: 0x18, p: 0x19, enter: 0x1c, a: 0x1e, s: 0x1f, d: 0x20, f: 0x21, g: 0x22, h: 0x23, j: 0x24, k: 0x25, l: 0x26, z: 0x2c, x: 0x2d, c: 0x2e, v: 0x2f, b: 0x30, n: 0x31, m: 0x32, space: 0x39, f1: 0x3b, f2: 0x3c, f3: 0x3d, f4: 0x3e, f5: 0x3f, f6: 0x40, f7: 0x41, f8: 0x42, f9: 0x43, f10: 0x44, up: 0x48, left: 0x4b, right: 0x4d, down: 0x50 };

export const fadeSteps = 0x30004;            // double: 20.0: number of fade steps (divisor) in the logo fade sub_102d1
export const bongHitTimer = 0x30be0;         // int32: countdown (0x5a) of the bong-hit pose (rasta state 0x3b)
export const gameState = 0x30be4;            // int32: program/menu state: 0x22 = start game (menu "play" button), 0x1c = back to menu (game over or quit confirmed), 0x25 = exit program; initial 1
export const idleTimer = 0x30be8;            // int32: frames without mouse movement/click before the rasta starts smoking (100)
export const level = 0x30bec;                // int32: current level (status bar "Level", saved with the high score, drives enemy selection in sub_159e7/sub_16446); starts at 1, +1 when a level ends
export const levelTimer = 0x30bf0;           // int32: frames left in the current level (0x438 at start); below 0 -> levelEnding = 1; below -0x21c all enemies are cleared
export const levelEndLoopState = 0x30bf4;    // int32: loop control of the level-complete sequence (sub_15e15): 0x22 running, set to 0x1c by sub_16837 when Jah has flown away
export const smokeGlowPhase = 0x30bf8;       // int32: phase of the idle smoking animation: 2 = joint glow brightening (DAC 0xb6), 0 = frames advancing, 1 = frames returning
export const cycleColors = 0x30c00;
export const CYCLECOLORS_FIELD = { SIZE: 0x8, rgb: 0x0 }; // 4 x 0x8-byte records: the 4 colours rotated through DAC entries 0xf9..0xfc by sub_14fba (red 3f/0/0, yellow 3f/3d/0, green 1/3c/0, grey 9/9/9: rasta colours)
export const musicTrack = 0x30c1c;           // int32: index 0..11 of the current music track (advanced when the song ends)
export const musicSamplesEnabled = 0x30c20;  // int32 (bool): play the f*.dwd digital samples along with the music tracks; toggled by the sound-menu checkbox, forced off when music volume < 0x96
export const highScoreRowColors = 0x30c24;
export const HIGHSCOREROWCOLORS_FIELD = { SIZE: 0x4, color: 0x0 }; // 10 x 0x4-byte records: text colour of each high-score row (copied to a local array and passed to Print_String_DB)
export const resetHighScores = 0x31ee0;      // int32 (bool): if nonzero sub_10676 re-initialises the high-score table (reading names from cin) before saving; 0 in the binary and never written (debug leftover)
export const pcxScratch = 0x31ee4;           // pcx_picture: scratch pcx_picture reused by every PCX_Init/PCX_Load/PCX_Delete group (sprite sheets, back.pcx, blank.pcx, howto.pcx, titp.pcx, hiscore.pcx, xlogo/evilx) (many files)
export const mainMenuPcx2 = 0x3227c;         // pcx_picture: main menu animation frame loaded from mainmnb2.pcx (copied to the double buffer in the menu loop) (mainmnb2.pcx)
export const mainMenuPcx3 = 0x32614;         // pcx_picture: main menu animation frame loaded from mainmnb3.pcx (copied to the double buffer in the menu loop) (mainmnb3.pcx)
export const mainMenuPcx = 0x329ac;          // pcx_picture: main menu animation frame loaded from mainmnb.pcx (copied to the double buffer in the menu loop) (mainmnb.pcx)
export const mainMenuPcx4 = 0x32d44;         // pcx_picture: main menu animation frame loaded from mainmnb4.pcx (copied to the double buffer in the menu loop) (mainmnb4.pcx)
export const mainMenuPcx5 = 0x330dc;         // pcx_picture: main menu animation frame loaded from mainmnb5.pcx (copied to the double buffer in the menu loop) (mainmnb5.pcx)
export const statusBar = 0x33918;            // sprite: top status bar ("Score  Kills  Level  Ganja Farmer", REGBAR.PNG) (regbar.pcx)
export const gunSight = 0x33aa4;             // sprite: mouse-driven aiming cursor (crosshair); x = mouseX/2 - 16, y = mouseY; also the menu pointer. curr_frame (0x33c0c) = 1 in menus, 0 in game; visible (0x33c2c) (gunsite.pcx)
export const van = 0x33c30;                  // sprite: John's 1969 VW microbus (static, drawn under the rasta) (van.pcx)
export const rasta = 0x33dbc;                // sprite: John Parker, the player (rasta with the gun on the van roof). curr_frame (0x33f24) = aim direction / weapon pose; state (0x33f2c): 1 aiming, 0x2b/0x2c idle joint-smoking animation, 0x3a/0x3b bong loading (rasta.pcx (40 frames, 4 rows: one row per weapon))
export const choppers = 0x33f48;             // 5 x sprite: enemy helicopters; drop paratroopers. counter_1 (+0x10) = x velocity, counter_2 (+0x14) = hit points (10), counter_3 (+0x18) = crash timer, state 0x1c/0x1b = flying right/left, 0x1a = crashing, 0 = respawn (chopper2.pcx)
export const explosions = 0x34704;           // 13 x sprite: explosion animations (ring buffer, next slot = explosionNext 0x60b8c); state 0x26 = pending, 1 = animating, 0 = idle (exp2.pcx)
export const paratroopers = 0x35b20;         // 25 x sprite: paratroopers descending under a parachute (dropped by choppers). state 0x1c/0x1b swinging down, 0x27 landing, 0x28 landed -> becomes a groundTroops entry, 0x21 chute shot (free fall, counter_2 = fall speed), 2/3/4 shot dying; 0 unused (ptroop.pcx (frames cut into entry 0, frame pointers copied to entries 1..24))
export const groundTroops = 0x381cc;         // 25 x sprite: landed paratroopers walking on the ground toward the herb (state 0x2f walk, 0x30 attacking a plant -> plant state 0x32, 0x2e/0x31 walking away); counter_3 (+0x18) = walk direction (1 right, 0 left) (pt2.pcx)
export const plants = 0x3a878;               // 26 x sprite: the herb (ganja plants) row at y=0x96, x = i*12. state 1 = growing, 0x32 = charge planted by a ground trooper (counter_2 fuse), 0x29 = burning (counter_1 = 180), 0x33 = regrowing (counter_3 timer, set by Jah / the "420" cheat), 0 = dead (frame 5) or abducted (frame 7). Game over when all states are 0 (plant.pcx)
export const a10Jets = 0x3d0b0;              // sprite: A-10 jet that crosses the sky dropping bombs; threshold_1 (+0x1c) = hit points (4), counter_1 = x velocity, counter_2 = entered-screen flag, counter_3 = bomb drop delay, state 1 flying / 0x2a bombing run (a-10.pcx (array loop with count 1))
export const bombs = 0x3d23c;                // 4 x sprite: bombs dropped by the A-10 (next slot = bombNext 0x60b9c); state 1 falling (counter_1 = vx, counter_2 = vy), explode at y >= 0xa0 burning plants; shooting one scores 501 (bomb.pcx)
export const cropDusters = 0x3d86c;          // 3 x sprite: crop-duster planes that spray herbicide on the plants; counter_1 = x velocity, counter_2 = hit points (4), counter_3 = spray duration, state 1 flying / 0x2d spraying (duster.pcx)
export const messageBox = 0x3dd10;           // sprite: dialog box; curr_frame (0x3de78): 0 "Level Done Mon", 1 "Praise Jah!!! more herb", 2 "GAME OVER", 3 "Jah say: Fight the power mon!" (RGDIABOX.PNG) (rgdiabox.pcx)
export const dusterSpray = 0x3de9c;          // 63 x sprite: herbicide spray droplets emitted by the crop dusters (ring, next slot = sprayNext 0x60bac); a droplet reaching the plant row kills a plant (cloud.pcx frame (0,0) (yellow puff))
export const scoreDigits = 0x44010;          // 7 x sprite: 7 digit sprites showing score (0x60a68) in the status bar / high-score table; curr_frame = digit (nums.pcx)
export const killsDigits = 0x44ae4;          // 5 x sprite: digit sprites showing kills (0x60a6c); 5 initialised, only 4 used (nums.pcx)
export const levelDigits = 0x452a0;          // 3 x sprite: 3 digit sprites showing the level (0x30bec) (nums.pcx)
export const volumeSliders = 0x45744;        // 3 x sprite: sound-menu slider knobs: [0] F/X volume (0x45744 -> dws_XDig), [1] music volume (0x458d0 -> dws_XMusic), [2] master volume (0x45a5c -> dws_XMaster). Separate Sprite_Init calls but contiguous (sndbuts.pcx)
export const soundMenu = 0x45be8;            // sprite: sound options panel; curr_frame (0x45d50) shows the music-samples checkbox (= musicSamplesEnabled == 0) (sndmenu.pcx)
export const jah = 0x45d74;                  // sprite: Jah on a cloud: bounces on the high-score screen; in game flies across every 5 levels dropping a powerup (state 0x1c/0x1b, 0x20 idle, threshold_3 0x45d98 = drop pass state 0x41/0x42/0x43); at level end descends and replants the herb (counter_2 0x45d88 = replant time = level*10 frames). threshold_1/2 = dx/dy on the high-score screen (jah.pcx)
export const missile = 0x45f00;              // sprite: homing rocket fired by the missile-launcher weapon (0x35); 5 direction frames; threshold_3 (0x45f24) = lifetime; state (0x46070) 1 = flying (missle.pcx)
export const missileTarget = 0x4608c;        // sprite: "DIE MON" lock-on marker placed at the gunsight when a missile is fired; follows the locked enemy (counter_2/counter_3 = dx/dy copied from the target) (diemon.pcx)
export const missileSmoke = 0x46218;         // 63 x sprite: smoke-trail puffs left by the missile (ring, next slot = missileSmokeNext 0x60eec); counter_1 = lifetime (cloud.pcx frame (1,0) (white puff))
export const ufo = 0x4c38c;                  // sprite: UFO that abducts a plant with a beam (target plant index 0x60bd0); threshold_2 (0x4c3ac) = hit points, counter_2 = vx, counter_3 = beam timer; 1000 points (ufo.pcx)
export const bongSmoke = 0x4c518;            // 200 x sprite: smoke clouds shot by the bong weapon (0x38): counter_1/counter_2 = velocity, state 1 = flying; hit enemies (cloud.pcx frame (2,0) (grey puff))
export const powerupDrop = 0x5fa78;          // sprite: weapon / bonus crate on a parachute dropped by Jah; curr_frame (0x5fbe0) = kind: 0 auto gun, 1 missile launcher, 2 bong, 3 +42000 points; state (0x5fbe8) 1 = falling (drpshoot.pcx)
export const cruiseMissile = 0x5fc04;        // sprite: cruise missile carrying a nuke; state 0x46/0x45 flying right/left, 0x44 detonated (threshold_1 0x5fc20 = flash countdown, burns every plant); appears from level 25 (sub_159e7) (crusmis.pcx)
export const nukeCloud = 0x5fd90;            // sprite: mushroom cloud shown when the cruise missile detonates; state (0x5ff00) 1 = visible (nuke.pcx)
export const bullets = 0x5ff20;
export const BULLETS_FIELD = { SIZE: 0x30, x: 0x0, y: 0x4, savedPixel: 0x8, active: 0xc, xStepTenths: 0x10, yStepTenths: 0x14, xStepCounter: 0x18, yStepCounter: 0x1c, vy: 0x20, vx: 0x28 }; // 60 x 0x30-byte records: machine-gun tracer bullets (single pixels) fired by the gun weapons (0x36/0x37) from the rasta toward the gunsight; each shot costs 1 point; hits damage choppers, bombs, A-10, dusters, cruise missile, UFO and paratroopers. sub_11c2a spawns (loops 59), sub_12130 moves/collides (60)
export const frameStartTime = 0x60a64;       // uint32: Timer_Query() at the start of a frame; frame pacing waits until the BIOS tick advances
export const score = 0x60a68;                // int32: player score (7 digits in the status bar, saved in highScores); +kill points, -1 per bullet
export const kills = 0x60a6c;                // int32: enemies killed (status bar "Kills", 4 digits)
export const highScores = 0x60a70;
export const HIGHSCORES_FIELD = { SIZE: 0x18, score: 0x0, level: 0x4, name: 0x8 }; // 9 x 0x18-byte records: high-score table, read from / written to scores.dat
export const mouseX = 0x60b48;               // int32: mouse x from Squeeze_Mouse(3) (0..639; gunsight x = mouseX/2 - 16)
export const mouseY = 0x60b4c;               // int32: mouse y from Squeeze_Mouse(3)
export const mouseButtons = 0x60b50;         // int32: mouse buttons from Squeeze_Mouse(3): 1 = left (fire / menu click), 2 = right (switch weapon)
export const frameCounter10 = 0x60b54;       // int32: frame counter cycling 0..10; bullets reload their sub-pixel step counters when >= 10
export const explosionDelays = 0x60b58;
export const EXPLOSIONDELAYS_FIELD = { SIZE: 0x4, delay: 0x0 }; // 13 x 0x4-byte records: start delay counters of the 13 explosions slots
export const explosionNext = 0x60b8c;        // int32: ring index (0..12) of the next explosions[] slot
export const explosionX = 0x60b90;           // int32: x of the explosion to spawn (read by sub_1352c)
export const explosionY = 0x60b94;           // int32: y of the explosion to spawn (+6 when stored)
export const paratrooperNext = 0x60b98;      // int32: index (0..24) of the last paratroopers[] slot used by a chopper drop
export const bombNext = 0x60b9c;             // int32: index (0..3) of the next bombs[] slot during an A-10 bombing run
export const colorCyclePhase = 0x60ba0;      // int32: phase 0..3 of the DAC 0xf9..0xfc colour rotation (sub_14fba)
export const prevGunSightX = 0x60ba4;        // int32: gunsight x of the previous frame (idle detection)
export const prevGunSightY = 0x60ba8;        // int32: gunsight y of the previous frame
export const dusterSprayNext = 0x60bac;      // int32: ring index (0..62) of the next dusterSpray[] slot
export const hasAutoGun = 0x60bb0;           // int32 (bool): automatic gun (weapon 0x37) collected (powerup kind 0 / cheat G+N)
export const hasMissileLauncher = 0x60bb4;   // int32 (bool): missile launcher (weapon 0x35) collected
export const hasBong = 0x60bb8;              // int32 (bool): bong weapon (0x38) collected
export const levelEnding = 0x60bbc;          // int32 (bool): set when levelTimer runs out: no new enemies spawn; when all enemies are gone the level-complete sequence runs and level++
export const allHerbDead = 0x60bc0;          // int32 (bool): 1 when every plant state is 0 (computed each frame) -> game over
export const inLevelEndSequence = 0x60bc4;   // int32 (bool): 1 while the level-complete sequence runs (suppresses the rasta idle reset in sub_18f27)
export const jahReplantX = 0x60bcc;          // int32: x of the first plant of the longest run of dead plants (-1 if none): where Jah flies to replant at level end
export const ufoTargetPlant = 0x60bd0;       // int32: index of the plant the UFO is abducting
export const savedPalette = 0x60bd4;         // RGB_palette: palette saved before the nuke flash and restored afterwards (-)
export const fireReady = 0x60edc;            // int32 (bool): gate for firing with the left button: default gun requires release between shots, the other weapons alternate every frame
export const randomVoice = 0x60ee0;          // int32: rand()%4 (or %3) choosing a random voice / scream sample
export const rastaAnimDelay = 0x60ee4;       // int32: frame-delay counter of the rasta smoking / bong animations (advance every 5 frames)
export const currentWeapon = 0x60ee8;        // int32: selected weapon: 0x36 default gun (semi-auto), 0x37 automatic gun, 0x35 missile launcher, 0x38 bong; right click cycles among owned ones
export const missileSmokeNext = 0x60eec;     // int32: ring index (0..62) of the next missileSmoke[] slot
export const bongState = 0x60ef4;            // int32: bong weapon phase: 0x39 = needs (re)loading (rasta plays bong animation), 0x3c = loaded and firing
export const bongShotsLeft = 0x60ef8;        // int32: frames of bong smoke left before reloading (0x3c)
export const bongBlowPending = 0x60efc;      // int32 (bool): play sndBongBlow on the next bong shot
export const rightButtonHeld = 0x60f00;      // int32 (bool): latch so one right click switches weapon only once
export const chopperSoundStatus = 0x60f04;
export const CHOPPERSOUNDSTATUS_FIELD = { SIZE: 0x2, status: 0x0 }; // 5 x 0x2-byte records: dws_DSoundStatus result words, one per chopper; chopper.dwd is replayed when 0 and the chopper is near the screen
export const sfxVolume = 0x60f0e;            // uint16: digital-effects volume 0..255 from the sound-menu slider (dws_XDig)
export const musicVolume = 0x60f10;          // uint16: music volume (dws_XMusic)
export const masterVolume = 0x60f12;         // uint16: master volume (dws_XMaster)
export const soundStatus = 0x60f14;          // uint16: result word of dws_DSoundStatus (bit 0 = still playing), shared scratch
export const songStatus = 0x60f16;           // uint16: result word of dws_MSongStatus (bit 0 = song playing)
export const ufoSoundStatus = 0x60f18;       // uint16: dws_DSoundStatus result for sndUfo2 (restart the loop when 0)
export const sndClickData = 0x60f20;         // pointer: Load_File buffer of click.dwd (copied into sndClick.snd)
export const sndDoubleClickData = 0x60f24;   // pointer: Load_File buffer of dclick.dwd (copied into sndDoubleClick.snd)
export const sndGunShotData = 0x60f28;       // pointer: Load_File buffer of gewtshot.dwd (copied into sndGunShot.snd)
export const sndYaMonData = 0x60f2c;         // pointer: Load_File buffer of yamon.dwd (copied into sndYaMon.snd)
export const sndSmokinData = 0x60f30;        // pointer: Load_File buffer of smokin.dwd (copied into sndSmokin.snd)
export const sndGetSomeData = 0x60f34;       // pointer: Load_File buffer of getsome.dwd (copied into sndGetSome.snd)
export const sndIShotData = 0x60f38;         // pointer: Load_File buffer of ishot.dwd (copied into sndIShot.snd)
export const sndChopperData = 0x60f3c;       // pointer: Load_File buffer of chopper.dwd (copied into sndChopper.snd)
export const sndRicochetData = 0x60f40;      // pointer: Load_File buffer of riq.dwd (copied into sndRicochet.snd)
export const sndExplosionData = 0x60f44;     // pointer: Load_File buffer of explo.dwd (copied into sndExplosion.snd)
export const sndParaDie1Data = 0x60f48;      // pointer: Load_File buffer of pdie1.dwd (copied into sndParaDie1.snd)
export const sndParaDie2Data = 0x60f4c;      // pointer: Load_File buffer of pdie2.dwd (copied into sndParaDie2.snd)
export const sndParaDie3Data = 0x60f50;      // pointer: Load_File buffer of pdie3.dwd (copied into sndParaDie3.snd)
export const sndPdie4Data = 0x60f54;         // pointer: Load_File buffer of pdie4.dwd (copied into sndPdie4.snd)
export const sndParaDie5Data = 0x60f58;      // pointer: Load_File buffer of pdie5.dwd (copied into sndParaDie5.snd)
export const sndParaSquishData = 0x60f5c;    // pointer: Load_File buffer of psquish.dwd (copied into sndParaSquish.snd)
export const sndGameOverData = 0x60f60;      // pointer: Load_File buffer of gameover.dwd (copied into sndGameOver.snd)
export const sndProtectData = 0x60f68;       // pointer: Load_File buffer of protect.dwd (copied into sndProtect.snd)
export const sndMissileData = 0x60f6c;       // pointer: Load_File buffer of missle.dwd (copied into sndMissile.snd)
export const sndLogoData = 0x60f70;          // pointer: Load_File buffer of Undlogo.dwd (copied into sndLogo.snd)
export const sndBongBubbleData = 0x60f74;    // pointer: Load_File buffer of bongbub.dwd (copied into sndBongBubble.snd)
export const sndBongBlowData = 0x60f78;      // pointer: Load_File buffer of bongblow.dwd (copied into sndBongBlow.snd)
export const sndBongData = 0x60f7c;          // pointer: Load_File buffer of bong.dwd (copied into sndBong.snd)
export const sndRastaRocketData = 0x60f80;   // pointer: Load_File buffer of rastarok.dwd (copied into sndRastaRocket.snd)
export const sndBongDeathData = 0x60f84;     // pointer: Load_File buffer of bongdth.dwd (copied into sndBongDeath.snd)
export const sndAutomaticData = 0x60f88;     // pointer: Load_File buffer of automan.dwd (copied into sndAutomatic.snd)
export const sndNukeData = 0x60f8c;          // pointer: Load_File buffer of nuke.dwd (copied into sndNuke.snd)
export const musicTrack0Data = 0x60f90;      // pointer: Load_File buffer of f0.dwm (copied into musicTrack0.track)
export const musicTrack2Data = 0x60f94;      // pointer: Load_File buffer of f2.dwm (copied into musicTrack2.track)
export const musicTrack1Data = 0x60f98;      // pointer: Load_File buffer of f1.dwm (copied into musicTrack1.track)
export const musicTrack3Data = 0x60f9c;      // pointer: Load_File buffer of f3.dwm (copied into musicTrack3.track)
export const sndMusicSample1Data = 0x60fa0;  // pointer: Load_File buffer of f1.dwd (copied into sndMusicSample1.snd)
export const sndMusicSample2Data = 0x60fa4;  // pointer: Load_File buffer of f2.dwd (copied into sndMusicSample2.snd)
export const sndMusicSample3Data = 0x60fa8;  // pointer: Load_File buffer of f3.dwd (copied into sndMusicSample3.snd)
export const sndMusicSample4Data = 0x60fac;  // pointer: Load_File buffer of f4.dwd (copied into sndMusicSample4.snd)
export const sndMusicSample5Data = 0x60fb0;  // pointer: Load_File buffer of f5.dwd (copied into sndMusicSample5.snd)
export const sndMusicSample6Data = 0x60fb4;  // pointer: Load_File buffer of f6.dwd (copied into sndMusicSample6.snd)
export const sndMusicSample65Data = 0x60fb8; // pointer: Load_File buffer of f65.dwd (copied into sndMusicSample65.snd)
export const sndMusicSample7Data = 0x60fbc;  // pointer: Load_File buffer of f7.dwd (copied into sndMusicSample7.snd)
export const sndMusicSample8Data = 0x60fc0;  // pointer: Load_File buffer of f8.dwd (copied into sndMusicSample8.snd)
export const sndMusicSample9Data = 0x60fc4;  // pointer: Load_File buffer of f9.dwd (copied into sndMusicSample9.snd)
export const sndMusicSample10Data = 0x60fc8; // pointer: Load_File buffer of f10.dwd (copied into sndMusicSample10.snd)
export const musicTrack4Data = 0x60fcc;      // pointer: Load_File buffer of f4.dwm (copied into musicTrack4.track)
export const musicTrack5Data = 0x60fd0;      // pointer: Load_File buffer of f5.dwm (copied into musicTrack5.track)
export const musicTrack6Data = 0x60fd4;      // pointer: Load_File buffer of f6.dwm (copied into musicTrack6.track)
export const musicTrack7Data = 0x60fd8;      // pointer: Load_File buffer of f7.dwm (copied into musicTrack7.track)
export const musicTrack8Data = 0x60fdc;      // pointer: Load_File buffer of f8.dwm (copied into musicTrack8.track)
export const musicTrack9Data = 0x60fe0;      // pointer: Load_File buffer of f9.dwm (copied into musicTrack9.track)
export const musicTrack10Data = 0x60fe4;     // pointer: Load_File buffer of f10.dwm (copied into musicTrack10.track)
export const sndUfoData = 0x60fe8;           // pointer: Load_File buffer of ufo.dwd (copied into sndUfo.snd)
export const sndUfo2Data = 0x60fec;          // pointer: Load_File buffer of ufo2.dwd (copied into sndUfo2.snd)
export const sndDetectOverrides = 0x60ff0;   // dws_DETECTOVERRIDES: STK hardware autodetect overrides (first 3 words 0xffff = autodetect) (-)
export const sndDetectResults = 0x61000;     // dws_DETECTRESULTS: STK detect results (opaque) (-)
export const sndIdeal = 0x61040;             // dws_IDEAL: STK ideal settings for dws_Init; +4 (0x61044) is reused as the rate output of dws_DGetRateFromDWD and passed to dws_DSetRate (-)
export const musicTrack1 = 0x61070;          // dws_MPLAY: music track f1.dwm (played in sequence by sub_10050) (f1.dwm)
export const musicTrack2 = 0x61080;          // dws_MPLAY: music track f2.dwm (played in sequence by sub_10050) (f2.dwm)
export const musicTrack3 = 0x61090;          // dws_MPLAY: music track f3.dwm (played in sequence by sub_10050) (f3.dwm)
export const musicTrack0 = 0x610a0;          // dws_MPLAY: music track f0.dwm (played in sequence by sub_10050) (f0.dwm)
export const musicTrack4 = 0x610b0;          // dws_MPLAY: music track f4.dwm (played in sequence by sub_10050) (f4.dwm)
export const musicTrack5 = 0x610c0;          // dws_MPLAY: music track f5.dwm (played in sequence by sub_10050) (f5.dwm)
export const musicTrack6 = 0x610d0;          // dws_MPLAY: music track f6.dwm (played in sequence by sub_10050) (f6.dwm)
export const musicTrack7 = 0x610e0;          // dws_MPLAY: music track f7.dwm (played in sequence by sub_10050) (f7.dwm)
export const musicTrack8 = 0x610f0;          // dws_MPLAY: music track f8.dwm (played in sequence by sub_10050) (f8.dwm)
export const musicTrack9 = 0x61100;          // dws_MPLAY: music track f9.dwm (played in sequence by sub_10050) (f9.dwm)
export const musicTrack10 = 0x61110;         // dws_MPLAY: music track f10.dwm (played in sequence by sub_10050) (f10.dwm)
export const sndClick = 0x61160;             // dws_DPLAY: menu click / name typing (click.dwd)
export const sndDoubleClick = 0x61180;       // dws_DPLAY: menu button / sound-menu toggle (dclick.dwd)
export const sndGunShot = 0x611a0;           // dws_DPLAY: gun weapons fire (gewtshot.dwd)
export const sndYaMon = 0x611c0;             // dws_DPLAY: "ya mon" voice: title, sound menu, random firing voice 1 of 4, high score entered (yamon.dwd)
export const sndSmokin = 0x611e0;            // dws_DPLAY: random firing voice 2 of 4 (smokin.dwd)
export const sndGetSome = 0x61200;           // dws_DPLAY: random firing voice 3 of 4; also when Jah arrives to replant (message "Praise Jah!!! more herb") (getsome.dwd)
export const sndIShot = 0x61220;             // dws_DPLAY: random firing voice 4 of 4 (ishot.dwd)
export const sndChopper = 0x61240;           // dws_DPLAY: helicopter rotor loop (chopper.dwd)
export const sndRicochet = 0x61260;          // dws_DPLAY: bullet hits an armoured enemy (chopper, A-10, duster, UFO) (riq.dwd)
export const sndExplosion = 0x61280;         // dws_DPLAY: explosions (explo.dwd)
export const sndParaDie1 = 0x612a0;          // dws_DPLAY: paratrooper scream (chute shot), random 1 of 3 (pdie1.dwd)
export const sndParaDie2 = 0x612c0;          // dws_DPLAY: paratrooper scream, random 2 of 3 (pdie2.dwd)
export const sndParaDie3 = 0x612e0;          // dws_DPLAY: paratrooper scream, random 3 of 3 (pdie3.dwd)
export const sndPdie4 = 0x61300;             // dws_DPLAY: played when the idle joint-smoking animation completes (+1000) (pdie4.dwd)
export const sndParaDie5 = 0x61320;          // dws_DPLAY: paratrooper body hit (pdie5.dwd)
export const sndParaSquish = 0x61340;        // dws_DPLAY: falling paratrooper hits the ground (psquish.dwd)
export const sndGameOver = 0x61360;          // dws_DPLAY: game over (sub_16b96) (gameover.dwd)
export const sndProtect = 0x61380;           // dws_DPLAY: played when Jah flies off after replanting (with message "Jah say: Fight the power mon!") (protect.dwd)
export const sndMissile = 0x613a0;           // dws_DPLAY: missile launch (weapon 0x35) (missle.dwd)
export const sndLogo = 0x613c0;              // dws_DPLAY: played once at start-up before the xlogo/evilx logo screens (name from Undlogo.dwd) (Undlogo.dwd)
export const sndBongBubble = 0x613e0;        // dws_DPLAY: bong loading (rasta state 0x3a->0x3b) (bongbub.dwd)
export const sndBongBlow = 0x61400;          // dws_DPLAY: bong weapon fire start (bongblow.dwd)
export const sndBong = 0x61420;              // dws_DPLAY: bong weapon loop (bong.dwd)
export const sndAutomatic = 0x61440;         // dws_DPLAY: automatic-gun pickup voice (automan.dwd)
export const sndRastaRocket = 0x61460;       // dws_DPLAY: missile-launcher pickup voice (rastarok.dwd)
export const sndBongDeath = 0x61480;         // dws_DPLAY: bong pickup voice (bongdth.dwd)
export const sndNuke = 0x614a0;              // dws_DPLAY: nuke detonation (nuke.dwd)
export const sndMusicSample1 = 0x614c0;      // dws_DPLAY: digital sample f1.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f1.dwd)
export const sndMusicSample2 = 0x614e0;      // dws_DPLAY: digital sample f2.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f2.dwd)
export const sndMusicSample3 = 0x61500;      // dws_DPLAY: digital sample f3.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f3.dwd)
export const sndMusicSample4 = 0x61520;      // dws_DPLAY: digital sample f4.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f4.dwd)
export const sndMusicSample5 = 0x61540;      // dws_DPLAY: digital sample f5.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f5.dwd)
export const sndMusicSample6 = 0x61560;      // dws_DPLAY: digital sample f6.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f6.dwd)
export const sndMusicSample65 = 0x61580;     // dws_DPLAY: digital sample f65.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f65.dwd)
export const sndMusicSample7 = 0x615a0;      // dws_DPLAY: digital sample f7.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f7.dwd)
export const sndMusicSample8 = 0x615c0;      // dws_DPLAY: digital sample f8.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f8.dwd)
export const sndMusicSample9 = 0x615e0;      // dws_DPLAY: digital sample f9.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f9.dwd)
export const sndMusicSample10 = 0x61600;     // dws_DPLAY: digital sample f10.dwd played together with a music track by sub_10050 when musicSamplesEnabled (f10.dwd)
export const sndUfo = 0x61620;               // dws_DPLAY: UFO beam (ufo.dwd)
export const sndUfo2 = 0x61640;              // dws_DPLAY: UFO hum loop (ufo2.dwd)
export const aimAngle = 0x61660;             // double: atan(dy/dx) from rasta to gunsight, used for bullet / bong-smoke velocity
export const jointGlowColor = 0x61668;       // RGB_color (3 bytes): colour written to DAC entry 0xb6 during the idle smoking animation (red channel ramps up)
export const paletteFade = 0x61670;
export const PALETTEFADE_FIELD = { SIZE: 0x38, rgb: 0x0, stepR: 0x8, stepG: 0x10, stepB: 0x18, accR: 0x20, accG: 0x28, accB: 0x30 }; // 255 x 0x38-byte records: per-DAC-entry fade-in state used by the logo screen fade (sub_102d1); entries 1..254 used, step = component / 20.0
export const doubleBuffer = 0x64e7c;         // pointer: library double_buffer (320x200 back buffer)
export const cin = 0x64eb8;                  // istream object: Watcom C++ cin, passed to istream >> char* in sub_10676
export const keyboardState = 0x64f04;        // int32[128], indexed by scan code (KEY): library keyboard_state[scan] (1 while key held). Game uses: Esc 0x64f08 quit prompt, F2 0x64ff4 sound menu, P 0x64f68 pause, Space 0x64fe8, Enter 0x64f74, Y 0x64f58 / N 0x64fc8 quit prompt, and cheat keys (see notes)
